[package]
name = "RustSampleAPI"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
odbc = "0.17"
serde = { version = "1.0", features = ["derive"] } # manipulação do JSON
serde_json = "1.0"